apiVersion: netsec/v1
kind: Group
metadata:
  name: api-tier
  owner: api-platform-team@company.com
  description: All API tier servers

spec:
  description: "API tier servers across all environments"
  
  membership:
    dynamic:
      match-labels:
        tier: api
        environment: production
        
    networks:
      - 10.100.2.0/24    # API subnet - East DC
      - 10.200.2.0/24    # API subnet - West DC

  platform-mapping:
    paloalto:
      strategy: hybrid
      dag:
        name: dag-api-tier
        match-criteria:
          - "'tier.api' and 'env.production'"
      static:
        name: grp-api-tier-static
        include-networks: true
      combined:
        name: grp-api-tier
        members:
          - type: dag
            ref: dag-api-tier
          - type: static
            ref: grp-api-tier-static

    illumio:
      strategy: label-based
      labels:
        - key: app
          value: api-tier
        - key: env
          value: production

    aws:
      strategy: security-group-preferred
      security-group:
        tag-key: netsec:group
        tag-value: api-tier
      cidr-fallback:
        enabled: true

    gcp:
      strategy: network-tag-preferred
      network-tag:
        tag: api-tier

    fortinet:
      strategy: address-group
      address-group:
        name: grp-api-tier

    azure:
      strategy: asg-preferred
      asg:
        name: asg-api-tier
        resource-group: rg-network-security
